### ISSUE TITLE
Image can't be initialized

### ISSUE THREAD

**Issue by eesnaola** [psliwa/PHPPdf#97]
Hello,

I am experiencing some problems when using the images with Twig . In fact, when I try to upload pictures from the server I'm always getting an "Image "/../../../logo.png" can not be initialized." 
 

My code looks like this:

```html
<!DOCTYPE pdf SYSTEM "%resources%/dtd/doctype.dtd">
 <pdf>
  <dynamic-page >
    <img src="{{pdf_image('HomeBundle:Resources/public/images/logo.png')}}"/>
  </dynamic-page >
</pdf>
```

the controller:

```php
public function caratulaAction($name)
 {
  $facade = $this->get('ps_pdf.facade');
  $response = new Response();
  $this->render('HomeBundle:Default:caratula.pdf.twig', array("name" => $name), $response);
  $xml = $response->getContent();
  $content = $facade->render($xml);
  return new Response($content, 200, array('content-type' => 'application/pdf'));
}
```

and the routing:

```yml
caratula:
    path:     /caratula/{name}.{_format}
    defaults: { _controller: HomeBundle:Default:caratula, _format: html}
    requirements:
        _format: html|pdf
```
Sorry for my bad English.
